name = 'Monospace Web'
license = 'MIT'
licenselink = 'https://github.com/rfaulahber/monospace-web-hugo/LICENSE'
description = 'Monospace Web for Hugo'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/rfaulahber/monospace-web-hugo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['monospace']
features = ['monospace']

# If the theme has a single author
[author]
  name = 'Ryan Faulhaber'
  homepage = 'https://github.com/rfaulhaber'

# If porting an existing theme
[original]
  author = 'Oskar Wickström'
  homepage = 'https://wickstrom.tech/'
  repo = 'https://github.com/owickstrom/the-monospace-web'
